app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/




Route::get('/', function() {
    return redirect('chooseQueue');
});


    Route::get('/liveQueue', [
        'as' => 'liveQueue',
        'uses' => function () {
            return view('liveQueue');
        }
    ]);

    Route::get('/inQueue', [
        'as' => 'inQueue',
        'uses' => function () {
            return view('inQueue');
        }
    ]);

    Route::get('/checkQueue', [
        'as' => 'checkQueue',
        'uses' => function () {
            return view('checkQueue');
        }
    ]);

      Route::get('/index', [
        'as' => 'index',
        'uses' => function () {
            return view('index');
        }
    ]);


/* login */
Route::get('/admin/login', 'AdminAuth\AuthController@showLoginForm');
Route::post('admin/login', 'AdminAuth\AuthController@login');

Route::get('/super-admin/login', 'SuperAdminAuth\AuthController@showLoginForm');
Route::post('/super-admin/login', 'SuperAdminAuth\AuthController@login');

    Route::get('/chooseQueue', [
        'as' => 'chooseQueue',
        'uses' => function () {
            return view('chooseQueue');
        }
    ]);

    
    Route::post('/store', [
        'as' => 'bots.store',
        'uses' => 'BotController@store'
    ]);


/* Admin access */
Route::group(['prefix' => 'admin', 'middleware' => 'admin'], function () {
   Route::get('/', 'AdminController@index');
   Route::get('/logout', 'AdminAuth\AuthController@logout');
   
   Route::resource('queues', 'QueueController', ['except' => [
       'index', 'show'
    ]]);
});

/* Super Admin access */
Route::group(
    [
        'prefix' => 'super-admin',
        'middleware' => 'super_admin'
    ],
    function () {
        Route::get('/', 'SuperAdminController@index');
        Route::get('/logout', 'SuperAdminAuth\AuthController@logout');
        Route::resource('queues', 'QueueController', ['except' => [
            'index', 'show'
        ]]);
    }
);

app/SuperAdmin.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;

class SuperAdmin extends Authenticatable
{
    //
}

app/Http/Controllers/SuperAdminController.php
<?php

namespace App\Http\Controllers;
use App\Queue;
use App\Admin;

use Illuminate\Support\Facades\Auth;

use App\Http\Requests;

class SuperAdminController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth:super_admin');
    }
    
    public function index()
    {
        $queues = Queue::all();
        $admins = Admin::all();
        return view('super-admins.index', [
            'queues' => $queues,
            'admins' => $admins
        ]);
    }

}

resources/views/super-admins/index.blade.php
@extends ('globals.layout')

@push('styles')
<link href="{{ asset('css/admin.css') }}" rel="stylesheet">
<link href="https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css" rel="stylesheet">
@endpush

@section ('navbar')
    @include ('super-admins.partials.navbar')    
@endsection

@section ('content')
<div class="container main-container ">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <h2>Colas Disponibles <a href="{{ route('super-admin.queues.create') }}" class="btn btn-primary text-uppercase create-queue">Crear Cola</a></h2> 
      <ul class="list-group">
        @foreach ($queues as $index => $queue)
        <li class="list-group-item">
          <div class="row">
            <div class="col-md-9">
              <h4 class="list-group-item-heading">{{ $index+1 }} - {{ $queue->name }}</h4>
            </div>
            <div class="col-md-3"> 
              {!! Form::open(['route' => ['super-admin.queues.destroy', $queue->id], 'method' => 'delete']) !!}
                <a href="{{ route('super-admin.queues.edit', ['id' => $queue->id]) }}" class="btn btn-default btn-sm">Editar</a>
                <button type="submit" class="btn btn-warning btn-sm delete-btn">Eliminar</button>
              {!! Form::close() !!}
            </div>
          </div>
          <h5>Estado de Atención</h5>
          {!! Form::open(['route' => ['super-admin.queues.update', $queue->id], 'method' => 'put', 'class' => 'formStatus', 'data-id' => $queue->id]) !!}
            <input type="checkbox" name="isenable" data-status="{{ $queue->status }}" data-id="{{ $queue->id }}" class="attentionStatus">
            <input type='hidden' name="disable" data-id="{{ $queue->id }}">
          {!! Form::close() !!}
        </li>
        @endforeach
      </ul>
      
      <hr>
      <h2>Administradores <a href="#" class="btn btn-primary text-uppercase create-queue">Nuevo Administrador</a></h2>
      <ul class="list-group">
        @foreach ($admins as $admin)
        <li class="list-group-item">
            <div class="row">
              <div class="col-md-9">
                <h4 class="list-group-item-heading">{{ $admin->name }}</h4>
              </div>
              <div class="col-md-3">
                <button type="button" class="btn btn-default btn-sm">Editar</button>
                <button type="button" class="btn btn-warning btn-sm delete-btn">Eliminar</button>
              </div>
            </div>
        </li>
        @endforeach
      </ul>
    </div>
  </div>
</div>
@endsection

@section('modal')
<div class="modal fade confirmDelete" tabindex="-1" role="dialog" aria-labelledby="confirmDeleteLabel">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-body"><h4>¿Está seguro que desea Eliminar este recurso?</h4></div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
        <button type="button" class="btn btn-warning">Eliminar</button>
      </div>
    </div>
  </div>
</div>
@endsection

@push('scripts')
<script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"></script>
<script src="{{ asset('js/delete-modal.js') }}"></script>
<script src="{{ asset('js/attention-status.js') }}"></script>
@endpush

resources/views/super-admins/login.blade.php
<h1>Super Admin Login</h1>
<form role="form" method="POST" action="{{ url('super-admin/login') }}">
    {!! csrf_field() !!}
    <div class="form-group">
      <label for="">Email</label>
      <input type="email" name="email" class="form-control" value="{{ old('email')}}" id="" placeholder="">
    </div>
    <div class="form-group">
      <label for="">Password</label>
      <input type="password" class="form-control" name="password" id="" placeholder="">
    </div>
    <button type="submit" name="submit-button" class="btn btn-sm btn-default btn-block">Entrar</button>
</form>